#include "./pvector.hpp"
int main(void)
{
  pvector<double,3> A, B, C;
  double val=0;
  pvector<int,3> iv={1,2,3};

  std::cout << "L'idea di questo programmino è ricordati come funziona la classe pvector!\n" << std::endl;
  std::cout << "Puoi definire l'oggetto scrivendo:\npvector<tipo,NT> nome;\nnel programma definiamo A,B,C di tipo double e lunghezza NT 3"<< std::endl;
  std::cout << "Il costruttore inizializza gli array come vettori nulli" << std::endl;
  std::cout << "Il metodo show ti permette di stamparli!\nStampiamo il vettore A con la seguente sintassi A.show(\"A = \")\n";
  A.show("A = ");
  std::cout << "Se voglio modificare il valore di un elemenro di un array posso usare il metodo set con la seguente sintassi: A.set(#,K), dove # è l'elemento e K il valore che imposto.\n";
  A.set(0,1);
  A.show("A = ");
  std::cout << "Il metodo get ti permette di prendere un valore da un array, con la seguente sintassi val = A.get(#) (posso usar anche A(0) )\n";
  std::cout << "val = " << val << " ora uso get";
  val = A(0);
  std::cout << "--> val = " << val << "\n";
  std::cout << "Posso anche assegnare un intero vettore, con l'operatore =, sintassi B=A\n";
  B = A;
  B.show("B =");
  std::cout <<"Posso sommare due vettori, con l'operatore +, sintassi C = A + B\nN.B. puoi anche scrivere C = A.sum(B)\n";
  C = A.sum(B);
  C.show("C = ");
  std::cout <<"Posso usare l'operatore +=, sintassi C += B\n";
  C+=B;
  C.show("C = ");
  std::cout<<"Posso usare l'operatore -, sintassi C = A - B\n";
  C = A - B;
  C.show("C = ");
  std::cout<<"Posso usare l'operatore -=, sintassi C -= B\n";
  C -= B;
  C.show("C = ");
  std::cout<<"Posso inizializzare un vettore con la seguente sintassi A ={1.,2.,3.}. Inizializzo A,B,C e li stampo.\n";
  A={1.,2.,3.};
  B={0.,1.,0.};
  C={0.,0.,1.};
  A.show("A = ");
  B.show("B = ");
  C.show("C = ");
  std::cout<<"Posso fare la norma dei vettori con A.norm()\n";
  val = A.norm();
  std::cout<< "norm = " << val << "\n";
  std::cout<<"Posso fare il prodotto scalare con la sintassi val = A * C\n";
  val = A * C;
  std::cout << "Prodotto scalare --> val = " << val << "\n";
  std::cout << "Posso moltiplicare scalare e vettore, con le seguenti sintassi A = val * B o A = B * val (puoi usar anche  B *= val)\n";
  A = B * val;
  A.show("A = ");
  std::cout << "Posso dividere per uno scalare, sintassi A = B / val (puoi usar anche B /= val)\n";
  A = B / val;
  A.show("A = ");
  std::cout << "E' stato implementato l'operatore confronto ==, sintassi A == B\n A == A -->"<< (A==A) <<"   A == B --> "<< (A==B) << "\n";
  std::cout <<"\nInizializzo di nuovo i vettori\n";
  A = {1.,0.,0.};
  B = {0.,1.,0.};
  C = {0.,0.,0.};
  A.show("A = ");
  B.show("B = ");
  C.show("C = ");
  std::cout <<"Posso effettuare il prodotto vettoriale, sintassi  C = A ^ B\n";
  C = A ^ B;
  C.show("C = ");
  std::cout <<"\nInizializzo di nuovo i vettori\n";
  A = {1.2,2.3,3.4};
  B = {5.1,1.1,0.7};
  C = {1.,2.5,0.9};
  A.show("A = ");
  B.show("B = ");
  C.show("C = ");
  std::cout << "Posso farne il rint(), con la sintassi A = rint(A)\n";
  A = rint(A);
  B = rint(B);
  C = rint(C);
  A.show("A = ");
  B.show("B = ");
  C.show("C = ");
  std::cout <<"Posso fare la component-wise moltiplication, con la sintassi B = A.mulcw(C)\n";
  B = A.mulcw(C);
  B.show("B = ");

  std::cout <<"Posso fare la component-wise division, con la sintassi B = A.divcw(C)\n";
  B = A.divcw(C);
  B.show("B = ");

  std::cout <<"Posso generare un vettore con componenti comprese tra [-L/2 , L/2], con la sintassi B = B.random(L)    (per noi L =  " << val <<")\n";
  B = B.random(val);
  B.show("B = ");

  std::cout <<"Questi son più o meno tutti i metodi utili a completare il progetto scelto!\n";
}
